name: Automated Issue Assignment

on:
  issues:
    types:
      - opened

jobs:
  assign:
    runs-on: ubuntu-latest

    steps:
    - name: Check for Keywords
      id: keyword-check
      run: |
        keywords=("bug" "feature" "enhancement")
        matched="false"
        for keyword in "${keywords[@]}"; do
          if grep -i "$keyword" $GITHUB_EVENT_PATH; then
            echo "::set-output name=matched::true"
            echo "::set-output name=keyword::$keyword"
            break
          fi
        done
      shell: bash

    - name: Assign Issue
      if: steps.keyword-check.outputs.matched == 'true'
      run: |
        echo "Assigning issue to ${{ steps.keyword-check.outputs.keyword }} team."
        # Use GitHub API to assign the issue to the appropriate team or user.
        # Example: Assign the issue to a team named "bugs" or "features."
      shell: bash
