name: Assign Issues to Teams

on:
  issues:
    types:
      - opened
      - edited

jobs:
  assign-issues:
    runs-on: ubuntu-latest

    steps:
      - name: Check if issue belongs to a specific label
        id: check-label
        run: |
          ISSUE_LABELS=$(jq -r '.issue.labels[].name' "${{ github.event_path }}")
          echo "::set-output name=label::$ISSUE_LABELS"
        shell: bash

      - name: Assign Issue to Team
        if: steps.check-label.outputs.label == 'team-label'
        run: |
          # Use the GitHub API to assign the issue to the desired team.
          # You will need to replace `your-organization` and `your-team` with your organization and team names.
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/orgs/your-organization/teams/your-team/memberships/${{ github.event.issue.user.login }} \
            -d ''
        shell: bash
