name: Assign Issues Based on Templates

on:
  issues:
    types:
      - opened

jobs:
  assign-issue:
    runs-on: ubuntu-latest

    steps:
      - name: Check Issue Template
        id: issue_template
        run: |
          ISSUE_TEMPLATE=$(jq -r .issue.template "${{ github.event_path }}")
          echo "::set-output name=template::$ISSUE_TEMPLATE"
        shell: bash

      - name: Assign Issue
        if: steps.issue_template.outputs.template == "bug_report"
        run: |
          echo "This is a Bug Report template. Assigning to the Bug Triage team."

        shell: bash

      - name: Assign Issue
        if: steps.issue_template.outputs.template == "feature_request"
        run: |
          echo "This is a feature Request template. Assigning to the feature team."

        shell: bash
        
